name: release
on:
  push:
    branches: [master, main, 'andrei/workflows/ruby-downloader']
    tags: ["*"]
    paths-ignore: ['**.md']
  workflow_dispatch: #allows manual trigger

concurrency: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Get next release version (dry run)
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: echo new tag
        run: |
          export NEXT_VERSION=${{ steps.taggerDryRun.outputs.new_tag }}
          echo "The next tag version will be: $NEXT_VERSION"
      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
      - name: Compile
        run: sbt clean stage
      - name: Generate Ruby Types
        run: ./standalone --withLanguageFrontend RUBYSRC 
      - name: Checksum
        run: sha512sum src/main/resources/ruby/builtin_types.zip > src/main/resources/ruby/builtin_types.zip.sha512
      - name: Rename
        run: |
          mv src/main/resources/ruby/builtin_types.zip ruby_builtin_types.zip
          mv src/main/resources/ruby/builtin_types.zip.sha512 ruby_builtin_types.zip.sha512
      - name: Show SHA512
        run: cat ruby_builtin_types.zip.sha512 
      - name: Set next release version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.taggerDryRun.outputs.new_tag }}
          files: |
            ruby_builtin_types.zip
            ruby_builtin_types.zip.sha512